/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osepcafe.pegawai;

import osepcafe.manager.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import osepcafe.koneksi;

/**
 *
 * @author sepae
 */
public class FrameTempat extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();

    /**
     * Creates new form FrameTempat
     */
    public FrameTempat() {
        initComponents();
        k.connect();
        refreshTable();
    }
    
    class Tempat extends FrameTempat{
        int id_meja, jumlah_kursi;
        String lokasi, status;
        
    public Tempat() {
        this.lokasi = comboLokasi.getSelectedItem().toString();
        this.jumlah_kursi = Integer.parseInt(comboJumlahKursi.getSelectedItem().toString()); 
        this.status = comboStatus.getSelectedItem().toString();
        }
    }

        public void refreshTable() {
        model = new DefaultTableModel();
        model.addColumn("ID Meja");
        model.addColumn("Lokasi");
        model.addColumn("Jumlah Kursi");
        model.addColumn("Status");

        tblTempat.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM tempat");
            this.rs = this.stat.executeQuery();

            while (rs.next()) {
                Object[] data = {
                    rs.getInt("id_meja"),
                    rs.getString("lokasi"),
                    rs.getInt("jumlah_kursi"),
                    rs.getString("status")
                };
                model.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        txtIdMeja.setText("");     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTempat = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtIdMeja = new javax.swing.JTextField();
        comboJumlahKursi = new javax.swing.JComboBox<>();
        comboLokasi = new javax.swing.JComboBox<>();
        comboStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTempat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTempat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTempatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTempat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 347, 750, 170));

        btnBack.setBackground(new java.awt.Color(210, 224, 224));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(64, 162, 227));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Edit");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        btnSave.setBackground(new java.awt.Color(101, 183, 65));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        txtIdMeja.setBackground(new java.awt.Color(64, 162, 227));
        txtIdMeja.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txtIdMeja, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 290, 30));

        comboJumlahKursi.setBackground(new java.awt.Color(64, 162, 227));
        comboJumlahKursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        comboJumlahKursi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        comboJumlahKursi.setName(""); // NOI18N
        getContentPane().add(comboJumlahKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 290, 30));

        comboLokasi.setBackground(new java.awt.Color(64, 162, 227));
        comboLokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lantai 1", "Lantai 2" }));
        comboLokasi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(comboLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 280, 30));

        comboStatus.setBackground(new java.awt.Color(64, 162, 227));
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Habis" }));
        comboStatus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        comboStatus.setName(""); // NOI18N
        getContentPane().add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/TempatFrame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    osepcafe.pegawai.PegawaiDashboard dashboardFrame = new osepcafe.pegawai.PegawaiDashboard();
    dashboardFrame.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Tempat u = new Tempat();
            this.stat = k.getCon().prepareStatement("insert into tempat values(?,?,?,?)");
            stat.setInt(1, 0); 
            stat.setString(2, u.lokasi);
            stat.setInt(3, u.jumlah_kursi);
            stat.setString(4, u.status);
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Tempat u = new Tempat();
        this.stat = k.getCon().prepareStatement("UPDATE tempat SET lokasi=?, jumlah_kursi=?, status=? WHERE id_meja=?");
        stat.setString(1, u.lokasi);
        stat.setInt(2, u.jumlah_kursi);
        stat.setString(3, u.status);
        stat.setInt(4, Integer.parseInt(txtIdMeja.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    try {
            Tempat u = new Tempat();
        this.stat = k.getCon().prepareStatement("DELETE FROM tempat WHERE id_meja=?");
        stat.setInt(1, Integer.parseInt(txtIdMeja.getText().trim()));
        stat.executeUpdate();
        refreshTable();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblTempatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTempatMouseClicked
        txtIdMeja.setText(model.getValueAt(tblTempat.getSelectedRow(),0).toString());
    }//GEN-LAST:event_tblTempatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTempat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTempat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTempat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTempat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTempat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboJumlahKursi;
    private javax.swing.JComboBox<String> comboLokasi;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTempat;
    public javax.swing.JTextField txtIdMeja;
    // End of variables declaration//GEN-END:variables
}
