/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osepcafe.pegawai;

import osepcafe.manager.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import osepcafe.*;


/**
 *
 * @author sepae
 */
public class FrameMakanan extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();

    /**
     * Creates new form FrameMakanan
     */
    public FrameMakanan() {
        initComponents();
        k.connect();
        refreshTable();
    }

    
    class Makanan extends FrameMakanan{
        int id_makanan, harga;
        String nama_makanan, status;
        
        public Makanan() {
            this.nama_makanan = txtNamaMakanan.getText();
            this.harga = Integer.parseInt(txtHargaMakanan.getText());
            this.status = comboMakanan.getSelectedItem().toString();
        }
    }
    
    public void refreshTable() {
        // Initialize the table model
        model = new DefaultTableModel();
        model.addColumn("ID Makanan");
        model.addColumn("Nama");
        model.addColumn("Harga");
        model.addColumn("Status");

        tblMakanan.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM makanan");
            this.rs = this.stat.executeQuery();

            while (rs.next()) {
                Object[] data = {
                    rs.getInt("id_makanan"),
                    rs.getString("nama_makanan"),
                    rs.getInt("harga"),
                    rs.getString("status")
                };
                model.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        txtIdMakanan.setText("");
        txtNamaMakanan.setText("");
        txtHargaMakanan.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtIdMakanan = new javax.swing.JTextField();
        txtHargaMakanan = new javax.swing.JTextField();
        txtNamaMakanan = new javax.swing.JTextField();
        comboMakanan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMakanan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(210, 224, 224));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 90, 30));

        btnSave.setBackground(new java.awt.Color(101, 183, 65));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 30));

        btnUpdate.setBackground(new java.awt.Color(64, 162, 227));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Edit");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, 30));

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, 30));

        txtIdMakanan.setBackground(new java.awt.Color(64, 162, 227));
        txtIdMakanan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtIdMakanan.setEnabled(false);
        getContentPane().add(txtIdMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 300, 30));

        txtHargaMakanan.setBackground(new java.awt.Color(64, 162, 227));
        txtHargaMakanan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txtHargaMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 300, 30));

        txtNamaMakanan.setBackground(new java.awt.Color(64, 162, 227));
        txtNamaMakanan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txtNamaMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 300, 30));

        comboMakanan.setBackground(new java.awt.Color(64, 162, 227));
        comboMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Habis" }));
        comboMakanan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(comboMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 222, 300, 30));

        tblMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMakanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMakananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMakanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 337, 770, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MakananFrame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    osepcafe.pegawai.PegawaiDashboard dashboardFrame = new osepcafe.pegawai.PegawaiDashboard();
    dashboardFrame.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Makanan u = new Makanan();
            this.stat = k.getCon().prepareStatement("insert into makanan values(?,?,?,?)");
            stat.setInt(1, 0); 
            stat.setString(2, u.nama_makanan);
            stat.setInt(3, u.harga);
            stat.setString(4, u.status);
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Makanan u = new Makanan();
        this.stat = k.getCon().prepareStatement("UPDATE makanan SET nama_makanan=?, harga=?, status=? WHERE id_makanan=?");
        stat.setString(1, u.nama_makanan);
        stat.setInt(2, u.harga);
        stat.setString(3, u.status);
        stat.setInt(4, Integer.parseInt(txtIdMakanan.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    try {
        Makanan u = new Makanan();
        this.stat = k.getCon().prepareStatement("DELETE FROM makanan WHERE id_makanan=?");
        stat.setInt(1, Integer.parseInt(txtIdMakanan.getText().trim()));
        stat.executeUpdate();
        refreshTable();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblMakananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMakananMouseClicked
            txtIdMakanan.setText(model.getValueAt(tblMakanan.getSelectedRow(),0).toString());
            txtNamaMakanan.setText(model.getValueAt(tblMakanan.getSelectedRow(),1).toString());
            txtHargaMakanan.setText(model.getValueAt(tblMakanan.getSelectedRow(),2).toString());
    }//GEN-LAST:event_tblMakananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboMakanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMakanan;
    private javax.swing.JTextField txtHargaMakanan;
    private javax.swing.JTextField txtIdMakanan;
    private javax.swing.JTextField txtNamaMakanan;
    // End of variables declaration//GEN-END:variables
}
