/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osepcafe.pegawai;

import osepcafe.*;
import osepcafe.FrameLogin;

/**
 *
 * @author sepae
 */
public class PegawaiDashboard extends javax.swing.JFrame {
    private User loggedInUser;
    /**
     * Creates new form FrameDashboard
     */
    public PegawaiDashboard(User loggedInUser) {
        this.loggedInUser = loggedInUser;
        initComponents();
        // Set labelNamaUser dengan nama pengguna yang login
        labelNamaUser.setText("Selamat datang, " + loggedInUser.getUsername());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMakanan = new javax.swing.JButton();
        btnMinuman = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnTempat = new javax.swing.JButton();
        labelNamaUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMakanan.setContentAreaFilled(false);
        btnMakanan.setBorderPainted(false);
        btnMakanan.setOpaque(false);
        btnMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakananActionPerformed(evt);
            }
        });
        getContentPane().add(btnMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 200, 70));

        btnMinuman.setContentAreaFilled(false);
        btnMinuman.setBorderPainted(false);
        btnMinuman.setOpaque(false);
        btnMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinumanActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 200, 70));

        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setBorderPainted(false);
        btnTransaksi.setOpaque(false);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 200, 70));

        btnLogout.setContentAreaFilled(false);
        btnLogout.setBorderPainted(false);
        btnLogout.setOpaque(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 80, 40));

        btnTempat.setContentAreaFilled(false);
        btnTempat.setBorderPainted(false);
        btnTempat.setOpaque(false);
        btnTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempatActionPerformed(evt);
            }
        });
        getContentPane().add(btnTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 343, 190, 80));

        labelNamaUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(labelNamaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PegawaiDashboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        FrameLogin loginFrame = new FrameLogin();
        loginFrame.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
    FrameTransaksi transaksiFrame = new FrameTransaksi();
    transaksiFrame.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakananActionPerformed
        // TODO add your handling code here:
    FrameMakanan userMakanan = new FrameMakanan();
    userMakanan.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnMakananActionPerformed

    private void btnMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinumanActionPerformed
        // TODO add your handling code here:
    FrameMinuman minumanFrame = new FrameMinuman();
    minumanFrame.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnMinumanActionPerformed

    private void btnTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempatActionPerformed
        // TODO add your handling code here:
    FrameTempat tempat = new FrameTempat();
    tempat.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnTempatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PegawaiDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PegawaiDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PegawaiDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PegawaiDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new PegawaiDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMakanan;
    private javax.swing.JButton btnMinuman;
    private javax.swing.JButton btnTempat;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNamaUser;
    // End of variables declaration//GEN-END:variables
}
