/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package osepcafe.manager;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import osepcafe.*;

/**
 *
 * @author sepae
 */
public class FrameMinuman extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();

    /**
     * Creates new form FrameMakanan
     */
    public FrameMinuman() {
        initComponents();
        k.connect();
        refreshTable();
    }

        class Minuman extends FrameMinuman{
        int id_minuman, harga;
        String nama_minuman, status;
        
        public Minuman() {
            this.nama_minuman = txtNamaMinuman.getText();
            this.harga = Integer.parseInt(txtHargaMinuman.getText());
            this.status = comboMinuman.getSelectedItem().toString();
        }
    }
        
    public void refreshTable() {
        // Initialize the table model
        model = new DefaultTableModel();
        model.addColumn("ID Minuman");
        model.addColumn("Nama");
        model.addColumn("Harga");
        model.addColumn("Status");

        tblMinuman.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM minuman");
            this.rs = this.stat.executeQuery();

            while (rs.next()) {
                Object[] data = {
                    rs.getInt("id_minuman"),
                    rs.getString("nama_minuman"),
                    rs.getInt("harga"),
                    rs.getString("status")
                };
                model.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        txtIdMinuman.setText("");
        txtNamaMinuman.setText("");
        txtHargaMinuman.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtIdMinuman = new javax.swing.JTextField();
        txtHargaMinuman = new javax.swing.JTextField();
        txtNamaMinuman = new javax.swing.JTextField();
        comboMinuman = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMinuman = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(210, 224, 224));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 100, 30));

        btnSave.setBackground(new java.awt.Color(101, 183, 65));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 30));

        btnUpdate.setBackground(new java.awt.Color(64, 162, 227));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Edit");
        btnUpdate.setFocusTraversalPolicyProvider(true);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, 30));

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, 30));

        txtIdMinuman.setBackground(new java.awt.Color(64, 162, 227));
        txtIdMinuman.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtIdMinuman.setEnabled(false);
        getContentPane().add(txtIdMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 300, 30));

        txtHargaMinuman.setBackground(new java.awt.Color(64, 162, 227));
        txtHargaMinuman.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtHargaMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaMinumanActionPerformed(evt);
            }
        });
        getContentPane().add(txtHargaMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 300, 30));

        txtNamaMinuman.setBackground(new java.awt.Color(64, 162, 227));
        txtNamaMinuman.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txtNamaMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 300, 30));

        comboMinuman.setBackground(new java.awt.Color(64, 162, 227));
        comboMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Habis" }));
        comboMinuman.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(comboMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 300, 30));

        tblMinuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMinuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMinumanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMinuman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 337, 770, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MinumanFrame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    osepcafe.manager.ManagerDashboard dashboardFrame = new osepcafe.manager.ManagerDashboard();
    dashboardFrame.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Minuman u = new Minuman();
            this.stat = k.getCon().prepareStatement("insert into minuman values(?,?,?,?)");
            stat.setInt(1, 0); 
            stat.setString(2, u.nama_minuman);
            stat.setInt(3, u.harga);
            stat.setString(4, u.status);
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Minuman u = new Minuman();
        this.stat = k.getCon().prepareStatement("UPDATE minuman SET nama_minuman=?, harga=?, status=? WHERE id_minuman=?");
        stat.setString(1, u.nama_minuman);
        stat.setInt(2, u.harga);
        stat.setString(3, u.status);
        stat.setInt(4, Integer.parseInt(txtIdMinuman.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    try {
        Minuman u = new Minuman();
        this.stat = k.getCon().prepareStatement("DELETE FROM minuman WHERE id_minuman=?");
        stat.setInt(1, Integer.parseInt(txtIdMinuman.getText().trim()));
        stat.executeUpdate();
        refreshTable();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblMinumanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMinumanMouseClicked
        txtIdMinuman.setText(model.getValueAt(tblMinuman.getSelectedRow(),0).toString());
        txtNamaMinuman.setText(model.getValueAt(tblMinuman.getSelectedRow(),1).toString());
        txtHargaMinuman.setText(model.getValueAt(tblMinuman.getSelectedRow(),2).toString());
    }//GEN-LAST:event_tblMinumanMouseClicked

    private void txtHargaMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaMinumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaMinumanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboMinuman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMinuman;
    private javax.swing.JTextField txtHargaMinuman;
    private javax.swing.JTextField txtIdMinuman;
    private javax.swing.JTextField txtNamaMinuman;
    // End of variables declaration//GEN-END:variables
}
